const express = require('express')
const router = express.Router()
const Controller = require('../controllers/renderController')
const {verifyManagerToken, verifyStudentToken, verifyAdminToken, verifyTeacherToken} = require('../middlewares/verify')
const {MANAGER_TOKEN_SECRET, STUDENT_TOKEN_SECRET, ADMIN_TOKEN_SECRET, TEACHER_TOKEN_SECRET} = process.env

router.get('/', Controller.getLogin)
router.get('/profile/manager/:id', verifyManagerToken(MANAGER_TOKEN_SECRET),Controller.getManager)
router.get('/profile/manager/:id/student/:studentId/:year/:month', verifyManagerToken(MANAGER_TOKEN_SECRET), Controller.payStudent)
router.get('/profile/teacher/:id', verifyTeacherToken(TEACHER_TOKEN_SECRET),Controller.getTeacher)
router.get('/profile/admin/:id', verifyAdminToken(ADMIN_TOKEN_SECRET),Controller.getAdmin)
router.get('/profile/admin/:id/school/manager/add', verifyAdminToken(ADMIN_TOKEN_SECRET),Controller.addManagerToSchool)
router.get('/profile/admin/:id/school/manager/update', verifyAdminToken(ADMIN_TOKEN_SECRET),Controller.updateSchoolManager)
router.get('/profile/admin/:id/manager/create', verifyAdminToken(ADMIN_TOKEN_SECRET),Controller.createManager)
router.get('/profile/admin/:id/teacher/create', verifyAdminToken(ADMIN_TOKEN_SECRET),Controller.createTeacher)
router.get('/profile/admin/:id/student/add', verifyAdminToken(ADMIN_TOKEN_SECRET),Controller.addStudent)
router.get('/profile/admin/:id/student/change', verifyAdminToken(ADMIN_TOKEN_SECRET),Controller.changeStudentAdmin)
router.get('/profile/student/:id', verifyStudentToken(STUDENT_TOKEN_SECRET),Controller.getStudent)
router.get('/profile/teacher/:id/student/create', verifyTeacherToken(TEACHER_TOKEN_SECRET),Controller.createStudent)
router.get('/profile/teacher/:id/student/change', verifyTeacherToken(TEACHER_TOKEN_SECRET),Controller.changeStudentTeacher)
router.get('/profile/teacher/:id/class/create', verifyTeacherToken(TEACHER_TOKEN_SECRET),Controller.createClass)
router.get('/profile/teacher/:id/class/add/students', verifyTeacherToken(TEACHER_TOKEN_SECRET),Controller.addStudentToClass)
router.get('/profile/teacher/:id/class/add/schedule', verifyTeacherToken(TEACHER_TOKEN_SECRET),Controller.createClassSchedule)
router.get('/profile/teacher/:id/class/add/lessons', verifyTeacherToken(TEACHER_TOKEN_SECRET),Controller.addLessons)
router.get('/profile/teacher/:id/class/update/lessons', verifyTeacherToken(TEACHER_TOKEN_SECRET),Controller.updateLessons)
router.get('/profile/teacher/:id/class/add/lesson/:selectedClassId/:selectedYear/:selectedMonth/:day', verifyTeacherToken(TEACHER_TOKEN_SECRET),Controller.getAttendance)
router.get('/profile/teacher/:id/class/update/lesson/:selectedClassId/:selectedYear/:selectedMonth/:day', verifyTeacherToken(TEACHER_TOKEN_SECRET),Controller.updateAttendance)

module.exports = router